# Capítulo 9 - Matemática e manipulação de matrizes com NumPy

## 1. NumPy

Site oficial: https://numpy.org

In [2]:
import numpy as np

In [3]:
# Checar a versão do NumPy

np.__version__

'2.1.3'

### Criando arrays NumPy

- Um arry NumPy é uma estrutura de dados multidimensional
- O NumPy fornece um objeto de matriz N-dimensional (ndarray)
- São mais eficientes que listas Python para lidar com grandes quantidade de dados
- Um array com apenas uma dimensão também é chamado de `vetor`
- É possível ter arrays com qualquer número de dimensões

In [4]:
arr1 = np.array([10,21,32,43,48,15,76,57,89])

In [5]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [7]:
#nd = número de dimensões

type(arr1)

numpy.ndarray

In [9]:
# Verificando o formato do array
arr1.shape

(9,)

## Indexação em arrays em NumPy

In [10]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [12]:
# Imprimindo um elemento específico no array
arr1[4]

np.int64(48)

In [13]:
# Indexação fatiando valores
arr1[1:4]

array([21, 32, 43])

In [14]:
# Para incluir o índice 4, uma outra possibilidade:
arr1[1:4+1]

array([21, 32, 43, 48])

In [15]:
# Criando uma lsita de índices
indices = [1,2,5,6]

# Imprimindo os elementos dos índices

arr1[indices]

array([21, 32, 15, 76])

In [16]:
# Criando uma máscara booleana para elementos pares

mask = (arr1 % 2 == 0)

# O resultado da operação vai ser uma lista de valores True ou False, dependendo da condição colocada

mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [17]:
# Agora, aplicamos essa variável para filtrar o array

arr1[mask]

array([10, 32, 48, 76])